# Generated by Django 4.2.16 on 2024-10-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_remove_product_id_product_date_added_product_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
