# Generated by Django 4.2.16 on 2024-11-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_product_sold_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
